import React from 'react';
import { Metadata } from 'next';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: 'Next.js tutorial',
    template: '%s | Codevolution',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={`${inter.className} h-screen flex items-start justify-between flex-col`}>
    <header className='w-full bg-blue-200 p-4'>
      <p>Header</p>
    </header>

    <main className='flex-grow w-full p-4'>
      {children}
    </main>

    <footer className='w-full bg-neutral-100 p-4'>
      <p>Footer</p>
    </footer>
    </body>
    </html>
  );
}
